spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: 7OwPSdVa1YydZBF3EjQM
            client-secret: YCYKXbM2ru
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email

          google:
            client-name: google
            client-id: 146398229574-1guehadtq6i590hf9flsq4pbsr0ndrg0.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi/naver.com/v1/nid/me
            user-name-attribute: response


